id: AA0D2AADA
title: 'True Words to Accomplish Immortality: A Longevity Prayer to the Tulku of Jamyang
  Khyentse, Thupten Chökyi Gyatso'
type: translation
pechas:
- IDA7A7DBD
- I36939E80
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:37:50.343643
  last_modified_at: 2023-01-04 11:37:50.343657
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IDA7A7DBD/572C: D270
  I36939E80/F623: D270
